### ISSUE TITLE
Dia 2 Exercicio 6

### ISSUE THREAD

**Issue by villasboas** [kayanevieira/30-Days-Of-JavaScript#1]
![image](https://user-images.githubusercontent.com/17419545/123100257-53c2c680-d409-11eb-92ca-ddac50b2e285.png)

Nesse exercicio era pra pegar a primeira palavra, nesse caso, voce pegou a primeira letra somente.

**Comment by kayanevieira** [comment]
fix error exercise 6. commit: 622260720442cf8e35435c798ee67012021e5873
