### ISSUE TITLE
Dia 2 exercicio 7

### ISSUE THREAD

**Issue by villasboas** [kayanevieira/30-Days-Of-JavaScript#2]
![image](https://user-images.githubusercontent.com/17419545/123100462-879dec00-d409-11eb-8dbf-70e6fabfef08.png)
 Nesse exercicio, voce deve remover a frase "Days of Javascript" da frase "30 Days of Javascript". Na sua implementação, esta removendo o 30.

Veja:

![image](https://user-images.githubusercontent.com/17419545/123100770-c8960080-d409-11eb-9431-5fbbdd4fb6c6.png)

**Comment by kayanevieira** [comment]
fix error of exercise 7. commit: 92c230874801e4cd2a0e36e17c9f7e5985cefbdb
